### PR TITLE
refactor: small refactor and improvements in bundler

### PR DESCRIPTION
**Pull request by ianaya89**
I hereby confirm that I followed the code guidelines found at [engineering guidelines](https://www.notion.so/checkly/Engineering-Guidelines-a3a165a203a04dc1a112f0e26b2f2d3f)

## ⚙️ Affected Components

- [ ] Commands
- [ ] Modules
- [x] Services
- [ ] SDK
- [ ] Tests

### 📝 Notes for the Reviewer

- Add `builtin-modules` to allow native node modules in check scripts
- Add initial setup for TS support
- Add bundle test cases
- Rename plugin to allowlist 

### 🏗️ New Dependency Submission

```diff
+ @rollup/plugin-typescript
+ builtin-modules
```

### CODE REVIEW

**Comment by umutuzgur** [comment]
@ianaya89 are you using npm 7 with node 14?

**Comment by ianaya89** [comment]
@umutuzgur npm 8 actually. Do you think this could be a problem? I can undo lock changes

**Comment by umutuzgur** [comment]
@ianaya89 They changed the format on npm 7. We are using npm 6 at the BE because that is the default npm version that comes with node 14

**Comment by ianaya89** [comment]
@umutuzgur reverted

**Review by umutuzgur — APPROVED** [review]

**Pull request merged**
