### PR TITLE
feat: create git-ignore if does not exists [sc-15241]

### PR DESCRIPTION
**Pull request by maxigimenez**
I hereby confirm that I followed the code guidelines found at [engineering guidelines](https://www.notion.so/checkly/Engineering-Guidelines-a3a165a203a04dc1a112f0e26b2f2d3f)

## Affected Components
* [ ] CLI
* [x] Create CLI
* [ ] Test
* [ ] Docs
* [ ] Examples
* [ ] Other

## Notes for the Reviewer
Allow the user to generate a `.gitignore` if none were present during the initialization of an existing project

### CODE REVIEW

**Review by ndom91 — COMMENTED** [review]
Maybe we just add this `.gitignore` as part of the "would you like us to initialize a git repo for you?" question. Instead of adding a whole new question in the wizard?

**Comment by maxigimenez** [comment]
@ndom91 @clample I've thinking about it after Nico's comment, and the best flow would be to ask if wanna initialize git, if so, we generate the `.git` and the `.gitignore` both for new and existing projects. wdyt?

**Comment by clample** [comment]
@maxigimenez I think that makes sense 👍

**Review by clample — APPROVED** [review]

**Review by ndom91 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
