### PR TITLE
Antoinecoutellier/sc 17815/add new multistepcheck constructor to the

### PR DESCRIPTION
**Pull request by Antoine-C**
I hereby confirm that I followed the code guidelines found at [engineering guidelines](https://www.notion.so/checkly/Engineering-Guidelines-a3a165a203a04dc1a112f0e26b2f2d3f)

## Affected Components
* [ ] CLI
* [ ] Create CLI
* [ ] Test
* [ ] Docs
* [ ] Examples
* [ ] Other

## Notes for the Reviewer

> Resolves #[issue-number]

### CODE REVIEW

**Comment by ndom91** [comment]
@Antoine-C what's the deal with this? I picked up the [sc-17814](https://app.shortcut.com/checkly/story/17814/update-public-api-to-allow-to-run-test-multi-steps-through-the-cli) ("Update public-api to allow 'run test' for multistep checks from cli"). But I need the constructs and what not for multistep to test it. So I added that under my `17814` ticket # as well (see: https://github.com/checkly/checkly-cli/pull/868).

How should we proceed? 

My PR with the multi-step construct seems to work. I have a little test checkly cli project with 1 multistep check in it using the space-x template that passes. It also returns the correct error when trying to use `context`, for example

**Comment by Antoine-C** [comment]
> @Antoine-C what's the deal with this? I picked up the [sc-17814](https://app.shortcut.com/checkly/story/17814/update-public-api-to-allow-to-run-test-multi-steps-through-the-cli) ("Update public-api to allow 'run test' for multistep checks from cli"). But I need the constructs and what not for multistep to test it. So I added that under my `17814` ticket # as well (see: #868).
> 
> How should we proceed?
> 
> My PR with the multi-step construct seems to work. I have a little test checkly cli project with 1 multistep check in it using the space-x template that passes. It also returns the correct error when trying to use `context`, for example

@ndom91 Feel free to pick this one up if it can unblock you, I won't have time this week to finish it 👍

**Comment by ndom91** [comment]
@Antoine-C okay great, thanks. Looks like everythign is working in https://github.com/checkly/checkly-cli/pull/868. I reused some of what you had here and credited you :wink: :pray:

**Comment by ndom91** [comment]
Superceded by: https://github.com/checkly/checkly-cli/pull/868

**Pull request closed without merging**
