### PR TITLE
feat: add verbose flag to show logs without failures [sc-0]

### PR DESCRIPTION
**Pull request by umutuzgur**
I hereby confirm that I followed the code guidelines found at [engineering guidelines](https://www.notion.so/checkly/Engineering-Guidelines-a3a165a203a04dc1a112f0e26b2f2d3f)

## Affected Components
* [x] CLI
* [ ] Create CLI
* [ ] Test
* [ ] Docs
* [ ] Examples
* [ ] Other

## Notes for the Reviewer
Add a verbose flag so it is easier to debug code

> Resolves https://github.com/checkly/checkly-cli/issues/490

### CODE REVIEW

**Comment by clample** [comment]
Do the reporters need to be updated as well?

**Comment by umutuzgur** [comment]
Good point, I didn't see that one

**Comment by umutuzgur** [comment]
@clample WDYT now?

**Review by clample — APPROVED** [review]
Looks great, I think that this will be useful. I like that it's behind a `--verbose` flag too.

**Pull request merged**
