### PR TITLE
chore: show help info with sorted commands [gh-723]

### LINKED ISSUE #723: feat: show help information sorted by CORE commands and ADDITIONAL commands
### What problem does this feature solve?

Currently, the oclif library makes a split between commands and topics. This is not user friendly, as it implies users to know what the difference is. It also sorts topics, like our `env` command to the top of the default help output.

We want to make a simpler split between:
- Core commands: test, deploy, trigger
- Additional commands: whoami, runtimes etc.

# Solution

The output should be similar to the following screenshot. Note that in the rough prototype, the `env` commands lists all its options. We don't want that.

CleanShot 2023-05-19 at 20 22 11@2x

# Acceptance criteria
- we mark core commands with an extra static property
CleanShot 2023-05-19 at 20 25 51@2x
- any other commands / topics are by default an additional command
- we disregard the oclif model of `Command` vs. `Topic` and sort, alphabetically, any core commands under the label `CORE COMMANDS` and additional commands under `ADDITIONAL COMMANDS`. 
- showing the help information for a command that is technically a `Topic`, i.e. the `env` command, is listed just with the label `COMMAND` as the hierarchy is irrelevant when accessing the help info for a specific command.

CleanShot 2023-05-19 at 20 29 42@2x

### How would you implement this feature?

We can override the rendering routines in oclif https://oclif.io/docs/help_classes as we are already doing in https://github.com/checkly/checkly-cli/blob/main/packages/cli/src/help/help-extension.ts

### PR DESCRIPTION
**Pull request by nahuelon**
I hereby confirm that I followed the code guidelines found at [engineering guidelines](https://www.notion.so/checkly/Engineering-Guidelines-a3a165a203a04dc1a112f0e26b2f2d3f)

## Affected Components
* [x] CLI
* [ ] Create CLI
* [ ] Test
* [ ] Docs
* [ ] Examples
* [ ] Other

## Notes for the Reviewer
Modify the `--help` information format, showing all commands treating the ones under topics as root commands. Commands are sorted by `CORE` and `ADDITIONAL` (default) categories.
Commands can be configured marked as `CORE COMMANDS` setting the `static coreCommand` property to `true`.

image

> Resolves #723

### CODE REVIEW

**Review by tnolet — CHANGES_REQUESTED** [review]
I found two bugs:
# `env` still fully expanded

The `env` command is fully expanded under `ADDITIONAL COMMANDS`. It should just be

```
VERSION
  checkly/4.0.6 darwin-arm64 node-v16.17.0

USAGE
  $ checkly [COMMAND]


CORE COMMANDS
  deploy   Deploy your project to your Checkly account.
  test     Test your checks on Checkly.
  trigger  Trigger checks on Checkly

ADDITIONAL COMMANDS
  autocomplete  display autocomplete installation instructions
  destroy       Destroy your project with all its related resources.
  env           Manage Checkly environment variables
  help          Display help for checkly.
  login         Login to your Checkly account or create a new one.
  logout        Log out and clear any local credentials.
  runtimes      List all supported runtimes and dependencies.
  switch        Switch user account.
  whoami        See your currently logged in account and user.undefined
```

# `user.undefined`

There us a `.undefined` after the `user` word in `whoami`

**Comment by tnolet** [comment]
> @tnolet , I fixed a `user.undefined` issue. About the topic separator, apparently there is a difference between Mac vs. Win/Lin systems where it's working OK. Let me know if the last commit fixes the `env` commands list. Thanks.
> 
> image

Hey @nahuelon I still see the `env` command fully expanded. It needs to look like this

```
ADDITIONAL COMMANDS
  autocomplete  display autocomplete installation instructions
  destroy       Destroy your project with all its related resources.
  env           Manage Checkly environment variables.
  help          Display help for checkly.
  login         Login to your Checkly account or create a new one.
  logout        Log out and clear any local credentials.
  runtimes      List all supported runtimes and dependencies.
  switch        Switch user account.
  whoami        See your currently logged in account and user.
```

**Comment by tnolet** [comment]
@nahuelon this works as described functionally, thanks. We should probably make any new command "ADDITIONAL" by default, as the goal is to the least amount of core commands to focus the user.

**Comment by nahuelon** [comment]
> @nahuelon this works as described functionally, thanks. We should probably make any new command "ADDITIONAL" by default, as the goal is to the least amount of core commands to focus the user.

Exactly. The `coreCommand` default value is `false`, so any new added command (without specifying the prop) will be "ADDIONATION". We must specifically set the `coreCommand = true` to show the command into the `CORE COMMANDS` list.

**Review by tnolet — APPROVED** [review]
LGTM!

**Pull request merged**
