### PR TITLE
chore: remove browserCheckDefaults from groups [sc-0]

### LINKED ISSUE #524: feat: clarify `apiCheckDefaults` and `browserCheckDefaults` in `CheckGroup`
### What problem does this feature solve?

Currently it's unclear how to use `apiCheckDefaults` and `browserCheckDefaults` in `CheckGroup`. The types are still `any` and we don't have much documentation for them ([relevant docs](https://www.checklyhq.com/docs/cli/constructs/#adding-checks-to-a-check-group)).

### How would you implement this feature?

From what I can see, both fields are stored in our backend and applied there, rather than being applied to constructs from the CLI. I suspect that `browserCheckDefaults` is never actually used - from a quick look, I don't see a way to set any browser check defaults in the Check Group page in the UI.

I propose that we:
1. Remove `browserCheckDefaults` from the `CheckGroup` construct
2. Either also remove `apiCheckDefaults` from the `CheckGroup` construct, or add better documentation and a more clear TS type.

### PR DESCRIPTION
**Pull request by nahuelon**
I hereby confirm that I followed the code guidelines found at [engineering guidelines](https://www.notion.so/checkly/Engineering-Guidelines-a3a165a203a04dc1a112f0e26b2f2d3f)

## Affected Components
* [x] CLI
* [ ] Create CLI
* [ ] Test
* [ ] Docs
* [ ] Examples
* [ ] Other

## Notes for the Reviewer
- remove `browserCheckDefaults` property from `CheckGroup` construct
- add type for `apiCheckDefaults`
- now `apiCheckDefaults` and `defaultApiCheckDefaults` are 'merged' (you could configure a subset of properties)
- add new tests for `test` command filtering and groups usages.

> Resolves #524

Important: we should deploy https://github.com/checkly/checkly-backend/pull/3900 first. Tests will fail until the `browserCheckDefaults` is optional.

### CODE REVIEW

**Comment by nahuelon** [comment]
After merging the PR, We have to remove the `browserCheckDefaults` property from the docs:

image

**Comment by umutuzgur** [comment]
@nahuelon you got the issue wrong. The issue is just about the removal of `browserCheckDefaults` field in `check-group.ts`

**Review by umutuzgur — CHANGES_REQUESTED** [review]
Check the PR comment

**Comment by nahuelon** [comment]
@umutuzgur , I misunderstood the `Session.browserCheckDefaults` attribute functionality. Now, I reverted the `browserCheckDefaults` config/session attribute removal.

**Comment by umutuzgur** [comment]
I think not sending `browserCheckDefaults` to the BE will return 404 in the testing case. We should handle this case and also write a test for it

**Comment by nahuelon** [comment]
@umutuzgur ,  what do you think in make the `browserCheckDefaults` attribute `.optional()` and `.strip()` it, within the backend schema? I found the `check_group` column allows `NULL` value so it's safe to remove it from the schema.

image

**Comment by umutuzgur** [comment]
Sounds good to me. I don't think we will ever use that anyways

**Comment by nahuelon** [comment]
@umutuzgur , I added more tests for the `test` command. I added a more complex test-project based in the advanced-project, so we can try more resources creation. For instance, now the test are failing until we make the `browserCheckDefaults` optional in the backend schema: https://github.com/checkly/checkly-backend/pull/3900

**Comment by umutuzgur** [comment]
@nahuelon could you finish this today or tomorrow?

**Comment by nahuelon** [comment]
@umutuzgur , I'm re-tackling this. The [backend PR](https://github.com/checkly/checkly-backend/pull/3900) is ready for review. We need it first to make the new tests (without the `browserCheckDefaults` prop) to pass.

**Review by umutuzgur — APPROVED** [review]
LGTM

**Pull request merged**
