### PR TITLE
feat: fix initial tests

### PR DESCRIPTION
**Pull request by ndom91**
I hereby confirm that I followed the code guidelines found at [engineering guidelines](https://www.notion.so/checkly/Engineering-Guidelines-a3a165a203a04dc1a112f0e26b2f2d3f)

## ⚙️ Affected Components
* [ ] Commands
* [ ] Modules
* [ ] Services
* [ ] SDK
* [x] Tests

### 📝 Notes for the Reviewer

Update existing tests / add new ones :+1:

### CODE REVIEW

**Comment by ndom91** [comment]
Good to go for this PR. Just merging the fixes to initial tests and the adjusted github action, so that we have some legit tests for forthcoming PRs / branches to use :tada: 

I had to set a default accountId (doesn't matter waht the value isi) in the config initialisation because I haven't quite figured out how to scaffold temporary `Conf` settings onto the tests. I have this `/test/helpers/config.js` file which is the left overs of my current attempt, but it doesn't work yet.. coming soon :tm:

**Comment by ianaya89** [comment]
@ndom91 I just added small cleanup of the test config. LMK if is ok, otherwise can revert them.

**Review by ianaya89 — DISMISSED** [review]
:shipit:

**Comment by ndom91** [comment]
Nice yeah good call, those weren't necessary anymore huh

**Comment by ndom91** [comment]
Okay this initial set seems good to go. Also passes in CI :thumsup:

**Pull request merged**
