### PR TITLE
feat: add `LocationCode` type for locations prop sanity [sc-00]

### PR DESCRIPTION
**Pull request by kiroushi**
I hereby confirm that I followed the code guidelines found at [engineering guidelines](https://www.notion.so/checkly/Engineering-Guidelines-a3a165a203a04dc1a112f0e26b2f2d3f)

### New dependency submission
Hint the users into using proper location codes instead of the unhelpful `string[]`.

### CODE REVIEW

**Comment by umutuzgur** [comment]
Is this restrictive to the list there or can a user add newer ones if they are on an older cli and we just released a new DC? If it

**Comment by kiroushi** [comment]
> Is this restrictive to the list there or can a user add newer ones if they are on an older cli and we just released a new DC?

@umutuzgur yes. Users can add a `global.d.ts` override like so:

```ts
declare module '@checkly/cli' {
  type LocationCode = string
}
```

I can add that to the docs.

**Comment by kiroushi** [comment]
I stand corrected: type augmentation doesn’t seem to be really straightforward, closing this for now.

**Comment by clample** [comment]
> I stand corrected: type augmentation doesn’t seem to be really straightforward, closing this for now.

@kiroushi does using `any` solve the issue? That should let users just bypass the type validation altogether.

**Pull request closed without merging**
